/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Blender3D (https://sketchfab.com/Blender3D)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/minecraft-chest-83c5b03288e9416fbe65616e45de2918
Title: Minecraft Chest
*/

import React, { forwardRef, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export const EliteLootBoxModel = forwardRef((props, ref) => {
  const { nodes, materials, animations } = useGLTF(
    "/3d/lootboxes/elite/scene.gltf"
  );
  const { actions } = useAnimations(animations, ref);
  return (
    <group ref={ref} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="chestfbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="Chest_0_A"
                  position={[-6.365, -87.985, 0]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <group name="Object_5">
                    <primitive object={nodes._rootJoint} />
                    <skinnedMesh
                      name="Object_12"
                      geometry={nodes.Object_12.geometry}
                      material={materials.Material}
                      skeleton={nodes.Object_12.skeleton}
                    />
                    <group
                      name="Object_11"
                      rotation={[-Math.PI / 2, 0, 0]}
                      scale={100}
                    />
                  </group>
                </group>
                <group
                  name="Chest_0"
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
});

useGLTF.preload("/scene.gltf");
